import { mockApi } from "@/api/mockApi";
import { GetServerSideProps } from "next";
import { Suspense } from "react";
import List from "@/components/List";
import { dehydrate, QueryClient } from "@tanstack/react-query";

import Head from "next/head";

export const getServerSideProps: GetServerSideProps = async () => {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery({
    queryFn: () => mockApi("prefetch 입니다~"),
    queryKey: ["key"],
  });

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Suspense fallback={<h1>loading...</h1>}>
          <List />
        </Suspense>
      </main>
    </>
  );
}
